// <auto-generated />
using System;
using Matrix_Task_anotherSolution.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Matrix_Task_anotherSolution.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220523154454_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.CategoryProps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryProps");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.ProductCategoryProp", b =>
                {
                    b.Property<int>("ProductPropId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryPropId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryPropsId")
                        .HasColumnType("int");

                    b.HasKey("ProductPropId", "CategoryPropId");

                    b.HasIndex("CategoryPropsId");

                    b.ToTable("ProductCategoryProps");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.ProductProp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductProp");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.CategoryProps", b =>
                {
                    b.HasOne("Matrix_Task_anotherSolution.Models.Category", "Category")
                        .WithMany("CategoryProps")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.Product", b =>
                {
                    b.HasOne("Matrix_Task_anotherSolution.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.ProductCategoryProp", b =>
                {
                    b.HasOne("Matrix_Task_anotherSolution.Models.CategoryProps", "CategoryProps")
                        .WithMany("ProductCategoryProps")
                        .HasForeignKey("CategoryPropsId");

                    b.HasOne("Matrix_Task_anotherSolution.Models.ProductProp", "ProductProp")
                        .WithMany("ProductCategoryProps")
                        .HasForeignKey("ProductPropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryProps");

                    b.Navigation("ProductProp");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.ProductProp", b =>
                {
                    b.HasOne("Matrix_Task_anotherSolution.Models.Product", "Product")
                        .WithMany("Props")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.Category", b =>
                {
                    b.Navigation("CategoryProps");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.CategoryProps", b =>
                {
                    b.Navigation("ProductCategoryProps");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.Product", b =>
                {
                    b.Navigation("Props");
                });

            modelBuilder.Entity("Matrix_Task_anotherSolution.Models.ProductProp", b =>
                {
                    b.Navigation("ProductCategoryProps");
                });
#pragma warning restore 612, 618
        }
    }
}
